config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: "Tu post fue correctamente guardado"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Tu post ha sido actualizado correctamente'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'El post ha sido eliminado'
  end

  private
    def post_params
      params.require(:post).permit(:date, :rationale)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiempoextra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">
  	<div class="row">
  		<div class="col-md-12">
        <%= render 'shared/nav' %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= js add_gritter(flash[:notice], title: "Notificaicón Ti-Ex", sticky: false) %>
  </body>
</html>

app/views/posts/.index.html.erb
<div class="flex-container">

    <div class="card box-sz">
      <img class="card-img-top" data-src="#" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Tiempo "#{}"</h4>
        <p class="card-text">Texto que le da contexto a la utilidad de la tarjeta. Asíncra.</p>
        <a href="#" class="btn btn-primary">accede</a>
      </div>
    </div>
  
    <div class="card box-sz">
      <img class="card-img-top" data-src="#" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Tiempo "#{}"</h4>
        <p class="card-text">Texto que le da contexto a la utilidad de la tarjeta. Asíncra.</p>
        <a href="#" class="btn btn-primary">accede</a>
      </div>
    </div>
  
    <div class="card box-sz">
      <img class="card-img-top" data-src="#" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Tiempo "#{}"</h4>
        <p class="card-text">Texto que le da contexto a la utilidad de la tarjeta. Asíncra.</p>
        <a href="#" class="btn btn-primary">accede</a>
      </div>
    </div>
  
    <div class="card box-sz">
      <img class="card-img-top" data-src="#" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Tiempo "#{}"</h4>
        <p class="card-text">Texto que le da contexto a la utilidad de la tarjeta. Asíncra.</p>
        <a href="#" class="btn btn-primary">accede</a>
      </div>
    </div>

</div>

app/views/posts/_form.html.erb
<br></br>
<%= form_for @post, :html => {class: "form-horizontal", role: "form"} do |f| %>

<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |error| %>
    <%= js add_gritter(error, title: "Notificaicón Ti-Ex", sticky: false) %>
  <% end %>
<% end %>

<div class="form-group">
  <%= f.label :Fecha  %>
  <%= f.date_field :date, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :Justificiación %>
  <%= f.text_area :rationale, class: "form-control" %>
</div>

  <%= f.submit "Guardar", class: "btn btn-primary btn-block" %>

<% end %>

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id %>
	</td>
	<td>
		<%= post.date %>
	</td>
	<td>
		<%= post.user.full_name %>
	</td>
	<td>
		<%= truncate(post.rationale) %>
	</td>
  <td><%= link_to 'Editar', edit_post_path(post), id: "edit_#{post.id}" %></td>
  <td><%= link_to 'Borrar', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", data: {confirm: '¿Estás seguro?'} %></td>
</tr>

app/views/posts/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Tiempos disponibles</h3>


<table class="table table-hover table-striped">
  <thead>
  	<tr>
  		<th>
  			#
  		</th>
  		<th>
  			Fecha
  		</th>
  		<th>
  			Usuario
  		</th>
  		<th>
  			Justificación
  		</th>
      <th></th>
      <th></th>
  	</tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Nuevo</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_nav.html.erb
<div class='logo'>
    <h1>Rastro de tiempo</h1>
</div>
<ul class="nav nav-tabs">
	<li class="nav-item">
    <a class="nav-link <%= active?(root_path) %>" href="http://localhost:3000/" >Base</a>
	</li>
	<li class="nav-item">
    <a class="nav-link <%= active?(posts_path) %>" href="http://localhost:3000/posts">Tiempos</a>
	</li>
	<li class="nav-item">
    <a id='new_post_from_nav' class="nav-link <%= active?(new_post_path) %>" href="http://localhost:3000/posts/new">Agregar Tiempos</a>
	</li>
	<li class="nav-item dropdown ml-md-auto">
		 <a class="nav-link dropdown-toggle <%= active?(edit_user_registration_path) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">Mi cuenta</a>
		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to "Editar", edit_user_registration_path, class:"dropdown-item" %>
			<div class="dropdown-divider">
			</div> <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
		</div>
	</li>
</ul>